### ISSUE TITLE
In OCR.ipynb , ModuleNotFoundError: No module named 'unidecode'

### ISSUE THREAD

**Issue by Avan-2608** [Breta01/handwriting-ocr#97] opened 2019-06-25 09:57 UTC
I am using windows, i am trying to run OCR.ipynb but it is giving me following error. I have already installed "unidecode" as mentioned in the environment.yml file.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-27e2f9a8fa94> in <module>()
     11 from ocr.helpers import implt, resize
     12 from ocr.tfhelpers import Model
---> 13 from ocr.datahelpers import idx2char

E:\handwriting-ocr-master\src\ocr\datahelpers.py in <module>()
     10 import csv
     11 import sys
---> 12 import unidecode
     13 
     14 from .helpers import implt

ModuleNotFoundError: No module named 'unidecode'

**Comment by Breta01** [comment] 2019-07-10 14:41
Weird, the unidecode should be installed if you used environment.yml. Anyways try installing it again with conda or pip.
```
pip3 install unidecode
```
That should solve the problem.

I am not able to reproduce this issue, so I will close it for now.

**Closed by Breta01** 2019-07-10 14:41 UTC
